export { Home } from './Home';
export { About } from './About';
export { Research } from './Research';
export { Projects } from './Projects';
export { Experience } from './Experience';
export { Education } from './Education';
export { Publications } from './Publications';
export { Skills } from './Skills';
export { Contact } from './Contact';
